name: test uv env workflow

on: #add your hook triggers in the array [push, pull, merge]
  push: # Trigger only on push events
    branches:
      - dev # Trigger only on pushes to the 'main' branch
  pull_request: # Trigger only on pull request events
    branches:
      - dev # Trigger only on pull requests targeting the 'main' branch
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  format-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup build environment
        uses: VITO-RS-Vegetation/veg-template@main # Reuse the composite action
        env:
          token: ${{ secrets.GITHUB_TOKEN }} # Use the built-in GITHUB_TOKEN for authentication
          UV_INDEX_VITO_ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          UV_INDEX_VITO_ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        with:
          uv-args: "--all-groups -vv"
